@startuml VacQ System Use Case Diagram
left to right direction
actor "User" as user
rectangle "VacQ System" as VacQSystem {    
    usecase "Register" as register
    usecase "View\nCar Providers" as viewCarProviders
    usecase "Manage\nBookings" as manageBookings
    usecase "Manage\nCar Providers" as manageCarProviders
}

user -- register
user -- viewCarProviders
user -- manageBookings

actor "Admin" as admin
register -- admin
manageCarProviders -- admin
manageBookings -- admin

@enduml